/**
 * Global Semantic Events 
 * Organized by domain/feature for easier tracking and maintenance across the system.
 */

export enum ActivityEvent {
  // --- AUTH DOMAIN ---
  APP_LOGIN_SUCCESS = 'APP_LOGIN_SUCCESS',
  
  // --- CV GENERATION DOMAIN ---
  CV_GENERATED_SUCCESS = 'CV_GENERATED_SUCCESS',
  CV_GENERATED_FAILED = 'CV_GENERATED_FAILED',
  
  // --- PROFILE DOMAIN ---
  PROFILE_PARSED_SUCCESS = 'PROFILE_PARSED_SUCCESS',
  PROFILE_PARSED_FAILED = 'PROFILE_PARSED_FAILED',
}

export enum SecurityEvent {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
}

export enum LedgerEvent {
  // Purchases
  BUY_CV_SLOT = 'MSG_BUY_CV_SLOT',
  BUY_CL_SLOT = 'MSG_BUY_CL_SLOT',
  
  // AI Generation
  GENERATE_CV_RESERVE = 'MSG_GENERATE_CV_RESERVE',
  GENERATE_CV_SUCCESS = 'MSG_GENERATE_CV_SUCCESS',
  GENERATE_CV_REFUND = 'MSG_GENERATE_CV_REFUND',
  
  // Profile Parsing
  PARSE_PROFILE_RESERVE = 'MSG_PARSE_PROFILE_RESERVE',
  PARSE_PROFILE_SUCCESS = 'MSG_PARSE_PROFILE_SUCCESS',
  PARSE_PROFILE_REFUND = 'MSG_PARSE_PROFILE_REFUND',
}
